name: cd
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build
        run: scripts/buildprod.sh
